name: Build Debian test Rootfs

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  Build:
    runs-on: ${{ matrix.config.os }}
    container:
      image: ${{ matrix.config.image }}
      options: --privileged
    name: ${{ matrix.config.name }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { 
              os: ubuntu-latest, 
              suite: trixie,
              arch: arm64,
              qemu-arch: "aarch64",
              name: 'Debian-trixie-arm64',
              kernel: 'linux-image-arm64',
              artifact: 'debian-trixie-arm64',
              hostname: 'debian-trixie-arm64',
              qcow2: 'debian-trixie-arm64.qcow2',
              rootfs: 'debian-trixie-arm64.tar.xz',
              pool: 'http://deb.debian.org/debian',
              image: 'lazymio/qemu-full:v7.2.8',
              iface: 'eth0'
            }
    steps:
    - uses: actions/checkout@v4

    - name: '🚧 Mount binfmt_misc'
      shell: bash
      run: |
        mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
        update-binfmts --display
        ls /opt/binfmt_fixed/ | awk '{print $1}' | xargs -L 1 update-binfmts --importdir /opt/binfmt_fixed --unimport
        ls /opt/binfmt_fixed/ | awk '{print $1}' | xargs -L 1 update-binfmts --importdir /opt/binfmt_fixed --import
        ls /opt/binfmt_fixed/ | awk '{print $1}' | xargs -L 1 update-binfmts --enable
        update-binfmts --display
    
    - name: '🚧 Dependency'
      shell: bash
      run: |
        apt update && apt install libguestfs-tools linux-image-generic debian-ports-archive-keyring aria2 -y
      
    - name: '🚧 Deboostrap 1st stage'
      shell: bash
      run: |
        mkdir mnt
        debootstrap --foreign --arch=${{ matrix.config.arch }} --include=locales ${{ matrix.config.suite }} mnt/ ${{ matrix.config.pool }}

    - name: '🚧 Deboostrap 2nd stage'
      shell: bash
      run: |
        chroot mnt/ debootstrap/debootstrap --second-stage

    - name: '🚧 Install Kernel & fstab'
      shell: bash
      run: |
        bash -c "echo 'fake /usr ext4 fake 0 1' > mnt/etc/fstab"
        chroot mnt/ apt update && chroot mnt/ apt install initramfs-tools -y
        sed -i 's/MODULES=most/MODULES=list/' mnt/etc/initramfs-tools/initramfs.conf
        
        {
          echo "virtio_mmio"
          echo "virtio_blk"
          echo "virtio_net"
          echo "virtio_pci"
          echo "ext4"
          echo "sd_mod"
          echo "xhci-pci"
          echo "uhci-hcd"
          echo "ehci-pci"
          echo "usb-storage"
          echo "uas"
          echo "usbhid"
          echo "usbnet"
          echo "ax88179_178a"
          echo "r8152"
          echo "cdc_ether"
        } >> mnt/etc/initramfs-tools/modules      
        
        chroot mnt/ apt update && chroot mnt/ apt install ${{ matrix.config.kernel }} -y
        bash -c "echo '/dev/vda / ext4 errors=remount-ro 0 1' > mnt/etc/fstab"
    
    - name: '🚧 Install SSH + sudo'
      shell: bash
      run: |
        chroot mnt/ apt install openssh-server sudo -y

    - name: '🚧 Configure SSH (Full Access)'
  shell: bash
  run: |
    echo "Port 22" > mnt/etc/ssh/sshd_config
    echo "ListenAddress 0.0.0.0" >> mnt/etc/ssh/sshd_config
    echo "ListenAddress ::" >> mnt/etc/ssh/sshd_config

    echo "PermitRootLogin yes" >> mnt/etc/ssh/sshd_config
    echo "PasswordAuthentication yes" >> mnt/etc/ssh/sshd_config
    echo "PubkeyAuthentication yes" >> mnt/etc/ssh/sshd_config

    echo "AllowTcpForwarding yes" >> mnt/etc/ssh/sshd_config
    echo "GatewayPorts yes" >> mnt/etc/ssh/sshd_config
    echo "AllowStreamLocalForwarding yes" >> mnt/etc/ssh/sshd_config
    echo "PermitTunnel yes" >> mnt/etc/ssh/sshd_config
    echo "AllowAgentForwarding yes" >> mnt/etc/ssh/sshd_config

    echo "X11Forwarding yes" >> mnt/etc/ssh/sshd_config
    echo "X11UseLocalhost no" >> mnt/etc/ssh/sshd_config

    echo "UsePAM yes" >> mnt/etc/ssh/sshd_config

    - name: '🚧 Configure Debian'
      shell: bash
      run: |
        bash -c "ls -lha mnt/etc/network/"
        bash -c "echo >> mnt/etc/network/interfaces"
        bash -c "echo 'auto ${{ matrix.config.iface }}' >> mnt/etc/network/interfaces"
        bash -c "echo 'iface ${{ matrix.config.iface }} inet dhcp' >> mnt/etc/network/interfaces"
        bash -c "cat /dev/null > mnt/etc/machine-id"
        bash -c "echo ${{ matrix.config.hostname }} > mnt/etc/hostname"

        chroot mnt bash -c "adduser --disabled-password --gecos '' debian"

        chroot mnt bash -c 'echo "root:root" | chpasswd'
        chroot mnt bash -c 'echo "debian:debian" | chpasswd'

        # Give full root access
        echo "debian ALL=(ALL:ALL) NOPASSWD: ALL" > mnt/etc/sudoers.d/debian
        chmod 440 mnt/etc/sudoers.d/debian

    - name: '📦 Pack qcow2'
      shell: bash
      run: |
        mkdir artifact
        virt-make-fs --type=ext4 --size=5G mnt raw.img
        qemu-img convert -c -f raw -O qcow2 raw.img artifact/${{ matrix.config.qcow2 }}

    - name: '📦 Pack Initrd & Kernel'
      shell: bash
      run: |
        cp mnt/boot/vmlinu* ./artifact/
        cp mnt/boot/initrd.img-* ./artifact/

    - name: '📦 Pack Rootfs'
      shell: bash
      run: |
        tar caf artifact/${{ matrix.config.rootfs }} --one-file-system mnt

    - name: '📤 Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        path: ./artifact/
        name: artifact-${{ matrix.config.arch }}

  publish:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          path: artifact
          merge-multiple: true

      - name: '📦 Check artifacts'
        shell: bash
        run: |
          ls -la artifact/
      
      - name: '📦 Release'
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: ./artifact/*
